logging:
  level:
    root: INFO

endpoint:
    from: timer:new-order?delay=1s&period=10s
    activemq: activemq:queue:HELLO.WORLD
    to: log:log-result

management:
  endpoints:
    web:
      exposure:
        include: hawtio,jolokia
  server:
    port: 8081

spring:
  jmx:
    enabled: true

hawtio:
  authenticationEnabled: false