scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['camel-prometheus:8080']
        labels:
          application: 'My Spring Boot Application'
